/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_qhu_qhuoj_judge_Runner */

#ifndef _Included_edu_qhu_qhuoj_judge_Runner
#define _Included_edu_qhu_qhuoj_judge_Runner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_qhu_qhuoj_judge_Runner
 * Method:    getRuntimeResult
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_edu_qhu_qhuoj_judge_Runner_getRuntimeResult
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
